import type { RouteModuleMeta } from './_meta-types'

export const MODULE: RouteModuleMeta = {
  file: 'store',
  routes: {
    'POST /api/store/query': {
      expose: 'ai',
      group: 'store',
      summary: 'Paginated search over store listings (primary browse endpoint)',
      body: '{"search":"weather","page":1,"pageSize":20}',
      returns: '{success:true,data:{items:[{slug,name,version,author,description,type,category,tags,...}],total?,hasMore,groups?:[{type,count,hasMore}],sources:[{registryId,status,error?}]}}',
      notes: 'All fields optional: search, type, category, page, pageSize, locale.',
    },
    'GET /api/store/apps': {
      expose: 'ai',
      group: 'store',
      summary: 'List store listings (legacy, non-paginated; prefer POST /api/store/query)',
      returns: '{success:true,data:[{slug,name,version,author,description,type,category,tags,...}]}',
      notes: 'Query params: search, locale, category, type, tags (comma-separated).',
    },
    'GET /api/store/apps/:slug': {
      expose: 'ai',
      group: 'store',
      summary: 'Get full detail for one store listing by slug',
      returns: '{success:true,data:{entry:{slug,name,version,...},spec:<AppSpec>,registryId}} or {success:false,error}',
    },
    'GET /api/store/app-document': {
      expose: 'ai',
      group: 'store',
      summary: "Get a listing's SKILL.md/README document",
      returns: '{success:true,data:{content:string|null}}',
      notes: 'slug is a query param (?slug=...), not a path segment — scoped slugs like "owner/repo" contain "/". content is null when the source has no document.',
    },
    'POST /api/store/install': {
      expose: 'ai',
      group: 'store',
      summary: 'Install an app from the store by slug',
      body: '{"slug":"author/app-id","spaceId":"$HALO_SPACE_ID"}',
      returns: '{success:true,data:{appId}} or {success:false,error,code?}',
      impact: 'reversible',
      notes: [
        'Always send spaceId, and send the right one. It is used exactly as sent: nothing fills it in and nothing checks it against the space you are working in. Omit it and the install goes GLOBAL; name another space and it installs there. Both answer success:true, and the response never says which space was written.',
        'Pass "spaceId":null only when the user explicitly asked for a global install (mcp/skill types only).',
        'Optional field: userConfig (object).',
        '400 = missing slug.',
        '403 with code=MCP_COMMAND_BLOCKED when the slug resolves to an MCP server blocked by build policy — do not retry, tell the user it is blocked.',
        'Same operation as POST /api/store/apps/:slug/install (slug in body vs in path); use either.',
      ].join('\n'),
    },
    'POST /api/store/apps/:slug/install': {
      expose: 'ai',
      group: 'store',
      summary: 'Install an app from the store by slug (REST-style path variant)',
      body: '{"spaceId":"$HALO_SPACE_ID"}',
      returns: '{success:true,data:{appId}} or {success:false,error,code?}',
      impact: 'reversible',
      notes: [
        'Always send spaceId, and send the right one. It is used exactly as sent: nothing fills it in and nothing checks it against the space you are working in. Omit it and the install goes GLOBAL; name another space and it installs there. Both answer success:true, and the response never says which space was written.',
        'Pass "spaceId":null only when the user explicitly asked for a global install (mcp/skill types only).',
        'Optional field: userConfig (object).',
        'Identical behavior to POST /api/store/install (slug in path instead of body), including the 403 MCP_COMMAND_BLOCKED case.',
      ].join('\n'),
    },
    'POST /api/store/refresh': {
      expose: 'ai',
      group: 'store',
      summary: 'Force a full re-download of the store registry index',
      returns: '{success:true,data:undefined}',
      notes: 'Heavier than POST /api/store/revalidate — use revalidate for a cheap freshness check.',
    },
    'GET /api/store/updates': {
      expose: 'ai',
      group: 'store',
      summary: 'List available updates for installed apps',
      returns: '{success:true,data:[{appId,currentVersion,latestVersion,entry,strategy,severity}]}',
    },
    'GET /api/store/registries': {
      expose: 'ai',
      group: 'store',
      summary: 'List configured store registry sources',
      returns: '{success:true,data:[{id,name,url,enabled,isDefault?,sourceType?,adapterConfig?:{...,"apiKey":"[redacted]"}}]}',
      notes: 'adapterConfig values (e.g. API keys) come back redacted.',
    },
    'GET /api/store/capabilities': {
      expose: 'ai',
      group: 'store',
      summary: 'Get which store features this build supports (publish, reviews, install counts)',
      returns: '{success:true,data:{catalog:true,installs:boolean,publish:boolean,reviewWorkflow:boolean,identity:"none"|string}}',
      notes: 'Reports what this build supports. Publishing itself is not open to you — if the user wants to publish, tell them to do it in the Halo app.',
    },
    'GET /api/store/category-taxonomy': {
      expose: 'ai',
      group: 'store',
      summary: 'Get the store category enum used for browsing and publishing',
      returns: '{success:true,data:{default:[{id,label|labelKey,icon?}],<appType>?:[...]}}',
      notes: 'Categories are keyed per app type (skill/automation/mcp/extension) with "default" as the fallback list for types without their own entry.',
    },
    'POST /api/store/revalidate': {
      expose: 'ai',
      group: 'store',
      summary: 'Cheap conditional freshness check for the store index',
      returns: '{success:true,data:{changed:boolean}}',
      notes: 'changed:false means the index did not move (a 304-equivalent); the browse list does not need refetching.',
    },
    'GET /api/store/discover-page': {
      expose: 'ai',
      group: 'store',
      summary: 'Get the curated store home page (featured/trending sections)',
      returns: '{success:true,data:{version,nodes:[{type,title?,subtitle?,entries?:[RegistryEntry],collections?,hasMore?}]}}',
      notes: 'Query params: locale?, pageSize?. Falls back to a single paginated catalog node when no curated layout is configured.',
    },
    'GET /api/store/my-publications': {
      expose: 'ai',
      group: 'store',
      summary: "List the signed-in creator's own published apps",
      returns: '{success:true,data:[{slug,name?,displayName?,type?,version,status:"listed"|"hidden"|"rejected",takedownBy?,rejectReason?,submittedAt?,channel?,installs?}]}',
      notes: 'Fails when no creator identity is signed in — this build may not support publishing at all (check GET /api/store/capabilities first).',
    },
    'POST /api/store/unpublish': {
      expose: 'ai',
      group: 'store',
      summary: "Take down one of the creator's own published apps",
      body: '{"slug":"author/app-id"}',
      returns: '{success:true,data:null}',
      impact: 'reversible',
      notes: 'Can be republished later; already-installed/downloaded copies elsewhere are not affected either way.',
    },
    'POST /api/store/ignore-version': {
      expose: 'ai',
      group: 'store',
      summary: 'Dismiss an available update so it stops appearing as pending',
      body: '{"appId":"<appId — a uuid from GET /api/apps>","version":"1.2.0"}',
      returns: '{success:true,data:null}',
      impact: 'reversible',
      notes: 'Only hides that one version; a newer update still surfaces normally.',
    },
    'POST /api/store/registries': {
      expose: 'ai',
      group: 'store',
      summary: 'Add a new registry source',
      body: '{"name":"My Registry","url":"https://example.com/registry"}',
      returns: '{success:true,data:{id,name,url,enabled,isDefault:false,sourceType?,adapterConfig?:{...,"apiKey":"[redacted]"}}} or {success:false,error}',
      notes: [
        'Optional fields: sourceType (string), adapterConfig (object, adapter-specific — e.g. an API key).',
        'url must be http(s) and not point to a loopback/private/link-local host. Fails if a registry with the same URL already exists.',
      ].join('\n'),
    },
    'DELETE /api/store/registries/:registryId': {
      expose: 'ai',
      group: 'store',
      summary: 'Remove a configured registry source',
      returns: '{success:true,data:undefined} or {success:false,error}',
      impact: 'reversible',
      notes: 'Fails with an error (not thrown) when the target is the built-in/default registry — those cannot be removed. Can be added back with POST /api/store/registries.',
    },
    'POST /api/store/registries/:registryId/toggle': {
      expose: 'ai',
      group: 'store',
      summary: 'Enable or disable a configured registry source',
      body: '{"enabled":true}',
      returns: '{success:true,data:undefined}',
      impact: 'reversible',
      notes: '400 if enabled is missing or not a boolean.',
    },
    'PATCH /api/store/registries/:registryId/adapter-config': {
      expose: 'ai',
      group: 'store',
      summary: "Update a registry source's adapter config (e.g. its API key)",
      body: '{"apiKey":"sk-..."}',
      returns: '{success:true,data:undefined}',
      impact: 'reversible',
      notes: [
        'Body is a flat JSON object of adapter-specific fields — exact keys depend on the registry\'s sourceType.',
        'Write-only: the response never echoes the config back, so this is safe for setting credentials. 400 if the body is missing or not a plain object.',
      ].join('\n'),
    },
    'POST /api/store/updates/check-now': {
      expose: 'ai',
      group: 'store',
      summary: 'Re-check all installed apps for available updates right now',
      returns: '{success:true,data:[{appId,currentVersion,latestVersion,entry,strategy,severity}]}',
      impact: 'reversible',
      notes: 'Apps set to auto-update silently apply any patch/minor update found — this is not just a read.',
    },
    'POST /api/store/updates/:appId/apply': {
      expose: 'ai',
      group: 'store',
      summary: 'Apply an available update to an installed app',
      body: '{"mode":"force"}',
      returns: '{success:true,data:{appId,from,to,severity}} or {success:false,error}',
      impact: 'reversible',
      notes: 'mode is optional: "patch_minor"|"major"|"force", defaults to "force". No built-in downgrade path — reinstalling the old version is the way back.',
    },
    'POST /api/store/publish/preview': {
      expose: 'ai',
      group: 'store',
      summary: 'Preview the slug and version a publish of an app would produce',
      body: '{"appId":"<appId — a uuid from GET /api/apps>"}',
      returns: '{success:true,data:{slug,localVersion,storeVersion:string|null}}',
      notes: 'Optional fields: author, name (override the store name before deriving the slug). storeVersion is null when the slug has never been published.',
    },
    'POST /api/store/publish/find-app': {
      expose: 'ai',
      group: 'store',
      summary: 'Find the installed app that a store slug would resolve to',
      body: '{"slug":"author/app-id"}',
      returns: '{success:true,data:{appId: string|null}}',
      notes: 'Optional fields: type, author. appId is null when no locally installed app uniquely matches.',
    },
    // The publish dispatcher's projectSpecForWire() (store/publish/dispatchers/
    // http-registry.ts:216-234) strips skill_files but never sanitizes
    // mcp.env/mcp.headers — publishing an installed MCP app with real
    // plaintext credentials in its spec uploads them to the public registry,
    // unrecoverable once live even after unpublishing. Not a response-body
    // leak (the redaction layer can't help): the action itself exfiltrates.
    'POST /api/store/publish': { expose: 'internal' },
    'POST /api/store/import-dhpkg': {
      expose: 'ai',
      group: 'store',
      summary: 'Install a digital human from a local .dhpkg file',
      body: '{"filePath":"/absolute/path/to/app.dhpkg","spaceId":"$HALO_SPACE_ID"}',
      returns: '{success:true,data:{appId}}',
      impact: 'reversible',
      notes: [
        'Installs and activates whatever the package contains — it starts running on its own schedule. Only import a file the user pointed you at. Undo with DELETE /api/apps/<appId>.',
        'A raw install: unlike the create_automation_app tool it does not fetch the package\'s required skills or roll back a half-finished install, so check GET /api/apps/<appId> afterwards rather than assuming.',
        'filePath is read with no sandbox check, so any path this machine can see resolves. That is not a licence to browse — pass through what the user gave you.',
        'spaceId is used exactly as sent — omitted means a global install, another space means it installs there, and neither is reported back. 400 when filePath is missing.',
        'Activation failing after install still returns success:true; check GET /api/apps/<appId> to confirm it is running.',
      ].join('\n'),
    },
  },
}
