import type { RouteModuleMeta } from './_meta-types'

/**
 * Internal code name for this module never appears in any exposed field
 * below — group is always 'knowledge-base', summaries say "collection".
 */
export const MODULE: RouteModuleMeta = {
  file: 'tlon',
  routes: {
    'POST /api/tlon': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'Create a knowledge collection',
      body: '{"name":"Product Docs"}',
      returns: '{success:true,data:{id,name,icon,description,status:"active",createdAt,updatedAt,path,linkedDirs:[],spaceIds:[],appIds:[],stats:{...}}}',
      notes: 'Optional fields: icon, description, linkedDirs (array of {path,label}).',
    },
    'GET /api/tlon': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'List all knowledge collections',
      returns: '{success:true,data:[{id,name,icon,description,status,spaceIds,appIds,stats,isDefault?,...}]}',
    },
    'GET /api/tlon/for-space/:spaceId': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'List knowledge collections bound to a space (or the default one)',
      returns: '{success:true,data:[{id,name,icon,description,status,...}]}',
    },
    'POST /api/tlon/set-default': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'Set (or clear) the collection new conversations auto-load',
      body: '{"kbId":"<kbId — a uuid from GET /api/tlon>"}',
      returns: '{success:true,data:<updated entry or null>}',
      impact: 'reversible',
      notes: 'kbId can be null to clear the default.',
    },
    'GET /api/tlon/:kbId': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'Get one knowledge collection by id',
      returns: '{success:true,data:{id,name,icon,description,status,linkedDirs,spaceIds,appIds,stats,...}} or {success:false,error:"Knowledge base not found"}',
    },
    'PUT /api/tlon/:kbId': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: "Rename or edit a collection's description/status",
      body: '{"name":"New name"}',
      returns: '{success:true,data:<updated entry>} or {success:false,error:"Knowledge base not found"}',
      impact: 'reversible',
      notes: 'All fields optional: name, icon, description, status ("active"|"paused"|"error").',
    },
    'DELETE /api/tlon/:kbId': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'Delete a knowledge collection and all its data',
      returns: '{success:true,data:<deletion result>}',
      impact: 'irreversible',
      narrowerAlternative: 'POST /api/tlon/:kbId/remove-raw',
      notes: 'Permanently deletes the collection\'s entire folder — original source files, extracted text, and the index. Not just the registry entry. If the user only meant to remove one document, use remove-raw instead.',
    },
    'POST /api/tlon/:kbId/bind-space': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'Bind a knowledge collection to a space',
      body: '{"spaceId":"<spaceId — a uuid from GET /api/spaces>"}',
      returns: '{success:true,data:<updated entry>}',
      impact: 'reversible',
      notes: '400 if spaceId is missing.',
    },
    'POST /api/tlon/:kbId/unbind-space': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'Unbind a knowledge collection from a space',
      body: '{"spaceId":"<spaceId — a uuid from GET /api/spaces>"}',
      returns: '{success:true,data:<updated entry>}',
      impact: 'reversible',
      notes: '400 if spaceId is missing.',
    },
    'POST /api/tlon/:kbId/bind-app': {
      expose: 'ai',
      group: ['knowledge-base', 'digital-human'],
      summary: 'Bind a knowledge collection so a digital human can read it',
      body: '{"appId":"<appId — a uuid from GET /api/apps>"}',
      returns: '{success:true,data:<updated entry>}',
      impact: 'reversible',
      notes: '400 if appId is missing.',
    },
    'POST /api/tlon/:kbId/unbind-app': {
      expose: 'ai',
      group: ['knowledge-base', 'digital-human'],
      summary: 'Unbind a knowledge collection from a digital human',
      body: '{"appId":"<appId — a uuid from GET /api/apps>"}',
      returns: '{success:true,data:<updated entry>}',
      impact: 'reversible',
      notes: '400 if appId is missing.',
    },
    'POST /api/tlon/:kbId/linked-dirs': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'Watch a server-local directory as a live document source',
      body: '{"path":"/Users/me/Documents/product-docs"}',
      returns: '{success:true,data:{id,path,label,watching,lastScannedAt?}} on success',
      notes: [
        'Optional field: label (defaults to path).',
        'Failure carries a code instead of throwing: TOO_MANY_FILES (data:{count,limit}), DISK_ROOT (cannot watch a filesystem root), FOLDER_TOO_LARGE, PATH_NOT_FOUND, KB_NOT_FOUND.',
        '400 if path is missing.',
      ].join('\n'),
    },
    'DELETE /api/tlon/:kbId/linked-dirs/:linkId': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'Stop watching a linked directory',
      returns: '{success:true,data:<removal result>}',
      impact: 'reversible',
      notes: 'Only removes the watch registration — the target folder and its files are untouched, and can be re-linked.',
    },
    'POST /api/tlon/:kbId/files': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'Add existing server-local files to a collection by absolute path',
      body: '{"filePaths":["/absolute/path/to/file.pdf"]}',
      returns: '{success:true,data:{added:string[],rejected:string[]}}',
      notes: '400 if filePaths is missing or empty. Files are copied in, not linked — see linked-dirs for live-watched folders.',
    },
    'GET /api/tlon/:kbId/raw': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'List the raw source files added to a collection',
      returns: '{success:true,data:[{name,path,size,learned:boolean,state:"learned"|"pending"|"no-text"|"failed",error?,source:"raw"|"linked",dirLabel?}]}',
    },
    'POST /api/tlon/:kbId/remove-raw': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'Remove one document (raw source file) from a collection',
      body: '{"relativePath":"raw/file.pdf"}',
      returns: '{success:true,data:<removal result>}',
      impact: 'irreversible',
      notes: '400 if relativePath is missing. Permanently deletes the copied file from the collection — no trash, no undo.',
    },
    'GET /api/tlon/:kbId/index': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: "Read a collection's document map (index.md)",
      returns: '{success:true,data:string}  — markdown text, empty string if not yet generated',
    },
    'POST /api/tlon/:kbId/resolve-sources': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'Map paths read from a collection back to their source documents',
      body: '{"readPaths":["/absolute/path/inside/the/collection"]}',
      returns: '{success:true,data:[{name:string,path:string}]}  — deduped, absolute, files that still exist',
      notes: 'Turns the copies a collection holds into citable originals. Paths that no longer exist are dropped silently, so a shorter list than you sent is normal. 400 when readPaths is not an array; an empty array is accepted and returns nothing.',
    },
    'POST /api/tlon/:kbId/ingest': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: "Start indexing a collection's documents (fire-and-forget)",
      returns: '{success:true,data:true}',
      notes: 'Returns immediately; the indexing job runs in the background. Poll GET /api/tlon/:kbId/ingest-status for progress — back off (2s, then double), do not tight-loop.',
    },
    'POST /api/tlon/:kbId/clear-relearn': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'Wipe extracted text and re-index a collection from scratch',
      returns: '{success:true,data:true} or {success:false,error:"Learning is already in progress"}',
      impact: 'reversible',
      notes: 'Use when documents were updated in place and stale extracted text needs replacing. Only clears derived/regeneratable data (extracted text, index) — original source files are untouched and text is rebuilt automatically.',
    },
    'GET /api/tlon/:kbId/ingest-status': {
      expose: 'ai',
      group: 'knowledge-base',
      summary: 'Get the current indexing progress for a collection',
      returns: '{success:true,data:{kbId,total,completed,current?,phase:"idle"|"running"|"done"|"error",error?,errors?:[{file,message}]}}',
    },
  },
}
